# Generated by Django 5.0 on 2023-12-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
