# Generated by Django 5.0 on 2023-12-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0002_customuser_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='FullName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='PhoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
