# Generated by Django 5.0 on 2023-12-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0004_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='field_name',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
