# Generated by Django 5.0 on 2023-12-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0005_customuser_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='field_name',
            new_name='photo',
        ),
    ]
