# Generated by Django 5.0.1 on 2024-02-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0008_customuser_favors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
