# Generated by Django 5.0.1 on 2024-02-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0009_alter_customuser_favors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favors',
        ),
    ]
